
    create table affectation (
        ens_id varchar(255),
        filiere_id varchar(255),
        id varchar(255) not null,
        matiere_id varchar(255),
        type varchar(255) not null check (type in ('COURS','TD','TP','PROJET_TUTORE')),
        ue_id varchar(255),
        primary key (id)
    );

    create table filiere (
        niveau integer,
        id varchar(255) not null,
        nom varchar(255),
        primary key (id)
    );

    create table matiere (
        coefficient float(53) not null,
        matiere_id varchar(255) not null,
        nom varchar(255) not null,
        ue_filiere_id varchar(255) not null,
        ue_ue_id varchar(255) not null,
        primary key (matiere_id, ue_filiere_id, ue_ue_id)
    );

    create table matiere_typeeval (
        type_eval_id bigint not null,
        filiere_id varchar(255) not null,
        matiere_id varchar(255) not null,
        ue_id varchar(255) not null,
        primary key (type_eval_id, filiere_id, matiere_id, ue_id)
    );

    create table moyenne_matiere (
        valeur float(53) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        etudiant_id varchar(255) not null,
        filiere_id varchar(255),
        matiere_id varchar(255),
        ue_id varchar(255),
        primary key (id),
        unique (etudiant_id, matiere_id, ue_id, filiere_id)
    );

    create table note (
        valeur float(53) not null,
        created_at timestamp(6) not null,
        note_id bigint generated by default as identity,
        type_eval_id bigint,
        etudiant_id varchar(255) not null,
        filiere_id varchar(255),
        matiere_id varchar(255),
        ue_id varchar(255),
        primary key (note_id),
        unique (etudiant_id, type_eval_id, matiere_id, filiere_id, ue_id)
    );

    create table notification (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        etudiant_id varchar(255),
        primary key (id)
    );

    create table t_user (
        otp_expiry timestamp(6),
        role varchar(31) not null,
        cin varchar(255) not null,
        email varchar(255) not null unique,
        filiere_id varchar(255),
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        nce varchar(255) unique,
        otp varchar(255),
        password varchar(255) not null,
        primary key (cin)
    );

    create table type_evaluation (
        coefficient float(53) not null,
        type_eval_id bigint generated by default as identity,
        labelle varchar(255) not null check (labelle in ('DS','EXAM','ORAL','TP')),
        primary key (type_eval_id)
    );

    create table unite_enseignement (
        coef integer,
        credits integer,
        filiere_id varchar(255) not null,
        nom varchar(255),
        ue_id varchar(255) not null,
        primary key (filiere_id, ue_id)
    );

    create table user_isimm (
        cin varchar(255) not null,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        primary key (cin)
    );

    alter table if exists affectation 
       add constraint FKqjqy3p795k16658dfd8bojjtk 
       foreign key (ens_id) 
       references t_user;

    alter table if exists affectation 
       add constraint FKiw2i9mqyf8vg0swi8i6elkqa5 
       foreign key (matiere_id, ue_id, filiere_id) 
       references matiere;

    alter table if exists matiere 
       add constraint FKhmul519j6dlili8phjjf3m8u8 
       foreign key (ue_filiere_id, ue_ue_id) 
       references unite_enseignement;

    alter table if exists matiere_typeeval 
       add constraint FKiocdx19pdnt6w3g9hvgynidnm 
       foreign key (type_eval_id) 
       references type_evaluation;

    alter table if exists matiere_typeeval 
       add constraint FKolwc66mm50o5bwpc4t78ou8fa 
       foreign key (matiere_id, filiere_id, ue_id) 
       references matiere;

    alter table if exists moyenne_matiere 
       add constraint FK6cy582s1a2kwfptg9qw4ftqbo 
       foreign key (etudiant_id) 
       references t_user;

    alter table if exists moyenne_matiere 
       add constraint FK5q0ggd76o8op3e5hk8talp44l 
       foreign key (matiere_id, filiere_id, ue_id) 
       references matiere;

    alter table if exists note 
       add constraint FK5pu7w9mj9mj8j0pm8n8essbvi 
       foreign key (etudiant_id) 
       references t_user;

    alter table if exists note 
       add constraint FKgqbhbqa9jxkh001ps18w6rcld 
       foreign key (matiere_id, filiere_id, ue_id) 
       references matiere;

    alter table if exists note 
       add constraint FKd8qiy95675yed4lytbqpnsl8y 
       foreign key (type_eval_id) 
       references type_evaluation;

    alter table if exists notification 
       add constraint FKqojypg7x4imoo2i0ja82xkx0i 
       foreign key (etudiant_id) 
       references t_user;

    alter table if exists t_user 
       add constraint FKnkr46kx1dnba1hxg1rieitm45 
       foreign key (filiere_id) 
       references filiere;

    alter table if exists unite_enseignement 
       add constraint FK5iyey80rwif735gxd0mkch2pu 
       foreign key (filiere_id) 
       references filiere;